name: Build exe
on: [workflow_dispatch]
jobs:
  build:
    name: Build exe
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm install
      - name: Build vite
        run: npm run build
      - name: Copy files
        run: copy dist\* electron\web
      - name: Install dependencies
        working-directory: ./electron
        run: npm install
      - name: Build electron
        working-directory: ./electron
        run: npm run build
      - name: Upload exe
        uses: actions/upload-artifact@v4
        with:
          name: canvas-plus
          path: ./electron/releases/canvas-plus-*-win.zip
